#!/bin/bash
hostnamectl set-hostname br-srv.au-team.irpo
exec bash
echo "192.168.1.2/28" > /etc/net/ifaces/ens18/ipv4address
echo "default via 192.168.1.1" > /etc/net/ifaces/ens18/ipv4route
echo "nameserver 192.168.100.2" > /etc/net/ifaces/ens18/resolv.conf
cd /etc/net/ifaces/ens18/
cat > options << EOF
TYPE=eth
BOOTPROTO=static
ONBOOT=yes
EOF
cd
systemctl restart network
sleep 10
useradd sshuser -u 2026
echo "sshuser:P@ssw0rd" | chpasswd
usermod -aG wheel sshuser
echo "sshuser ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers
cd /etc/openssh/
cat << EOF >> sshd_config
Port 2026
AllowUsers sshuser
MaxAuthTries 2
Banner /etc/openssh/banner
EOF
cd
echo "Authorized access only" > /etc/openssh/banner
systemctl enable sshd
systemctl restart sshd
systemctl restart network

