#!/bin/bash
en
con
hostname hq-rtr.au-team.irpo
interface ISP
ip address 172.16.1.2/28
exit
port te0
service-instance te0/ISP
encapsulation untagged
connect ip interface ISP
end
con
interface vl100
ip address 192.168.100.1/27
exit
interface vl200
description "VLAN 200"
ip address 192.168.200.1/24
exit
interface vl999
description "VLAN 999"
ip address 192.168.99.1/29
end
con
port te1
service-instance te1/vl100
encapsulation dot1q 100 exact
rewrite pop 1
connect ip interface vl100
exit
service-instance te1/vl200
encapsulation dot1q 200 exact
rewrite pop 1
connect ip interface vl200
exit
service-instance te1/vl999
encapsulation dot1q 999 exact
rewrite pop 1
connect ip interface vl999
end
con
ip route 0.0.0.0/0 172.16.1.1
interface tunnel.0
ip address 10.10.10.1/30
ip tunnel 172.16.1.2 172.16.2.2 mode gre
end
con
router ospf 1
ospf router-id 10.10.10.1
passive-interface default
no passive-interface tunnel.0
no passive-interface vl100
no passive-interface vl200
no passive-interface vl999
network 10.10.10.0/30 area 0
network 192.168.100.0/27 area 0
network 192.168.200.0/24 area 0
network 192.168.99.0/29 area 0
end
con
interface tunnel.0
ip ospf authentication message-digest
ip ospf message-digest-key 1 md5 P@ssw0rd
end
con
ntp timezone utc+5
ip pool VLAN200 
range 192.168.200.10-192.168.200.10
dhcp-server 1
pool VLAN200 1
mask 28
gateway 192.168.200.1
dns 192.168.100.2
domain-name au-team.irpo
end
con
interface vl200
dhcp-server 1
end
con
username net_admin
password P@ssw0rd
role admin
end
con
interface ISP
ip nat outside
interface vl100
ip nat inside
interface vl200
ip nat inside
interface vl999
ip nat inside
exit
ip nat pool HQ-RTR 192.168.99.1-192.168.200.254
ip nat source dynamic inside-to-outside pool HQ-RTR overload interface ISP
end
con
pppoe-profile 1
dns ipv4 192.168.100.2
end
wr
