#!/bin/bash
hostnamectl set-hostname hq-srv.au-team.irpo
exec bash
mkdir -p /etc/net/ifaces/ens18
echo "192.168.100.2/27" > /etc/net/ifaces/ens18/ipv4address
echo "default via 192.168.100.1" > /etc/net/ifaces/ens18/ipv4route
echo "nameserver 77.88.8.8" > /etc/net/ifaces/ens18/resolv.conf
cd /etc/net/ifaces/ens18/
cat > options << EOF
TYPE=eth
BOOTPROTO=static
ONBOOT=yes
EOF
cd
systemctl restart network
sleep 10
useradd sshuser -u 2026
echo "sshuser:P@ssw0rd" | chpasswd
usermod -aG wheel sshuser
echo "sshuser ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers
cd /etc/openssh/
cat << EOF >> sshd_config
Port 2026
AllowUsers sshuser
MaxAuthTries 2
Banner /etc/openssh/banner
EOF
cd
echo "Authorized access only" > /etc/openssh/banner
systemctl enable sshd
systemctl restart sshd
sleep 10
apt-get update && apt-get install bind bind-utils -y
cd /etc/bind
sed -i "s/listen-on { 127.0.0.1; };/listen-on { 192.168.100.2; };/g" /etc/bind/options.conf
sed -i "s/forwarders { };/forwarders { 77.88.8.8; };/g" /etc/bind/options.conf
sed -i "s/allow-query { localnets; };/allow-query { any; };/g" /etc/bind/options.conf
sed -i "24s/[//]//g" /etc/bind/options.conf
sed -i "29s/[//]//g" /etc/bind/options.conf
cat << EOF >> rfc1912.conf

zone "au-team.irpo" {
        type master;
        file "au-team.irpo";
};

zone "0.168.192.in-addr.arpa" {
        type master;
        file "0.168.192.in-addr.arpa";
};

EOF

cd zone
cat > au-team.irpo << 'EOF'
$TTL    1D
@       IN      SOA     au-team.irpo. root.au-team.irpo. (
                                2025110500      ; serial
                                12H             ; refresh
                                1H              ; retry
                                1W              ; expire
                                1H              ; ncache
                        )
        IN      NS      au-team.irpo.
        IN      A       127.0.0.1
hq-srv  IN      A       192.168.100.2
hq-cli  IN      A       192.168.200.10
hq-srv  IN      A       192.168.100.2
hq-rtr  IN      A       192.168.100.1
hq-rtr  IN      A       192.168.200.1
hq-rtr  IN      A       192.168.99.1
docker  IN      A       172.16.1.1
web     IN      A       172.16.2.1
br-srv  IN      A       192.168.1.2
br-rtr  IN      A       192.168.1.1
EOF
cat > 0.168.192.in-addr.arpa << 'EOF'
$TTL    1D
@       IN      SOA     0.168.192. root.0.168.192. (
                                2025110500      ; serial
                                12H             ; refresh
                                1H              ; retry
                                1W              ; expire
                                1H              ; ncache
                        )
        IN      NS      0.168.192.
1 IN PTR hq-rtr.au-team.irpo.
2 IN PTR hq-srv.au-team.irpo.
3 IN PTR hq-cli.au-team.irpo.
4 IN PTR br-rtr.au-team.irpo.
5 IN PTR br-srv.au-team.irpo.

EOF
chmod 777 au-team.irpo
chmod 777 0.168.192.in-addr.arpa
echo "nameserver 192.168.100.2" > /etc/net/ifaces/ens18/resolv.conf
systemctl enable --now bind.service
echo "192.168.100.1   hq-rtr.au-team.irpo" >> /etc/hosts
echo "192.168.100.2   hq-srv.au-team.irpo" >> /etc/hosts
echo "192.168.200.10   hq-cli.au-team.irpo" >> /etc/hosts
echo "192.168.1.1   br-rtr.au-team.irpo" >> /etc/hosts
echo "192.168.1.2   br-srv.au-team.irpo" >> /etc/hosts
systemctl restart network


